version: "3.0"

services:
  local_db:
    image: postgres:16-alpine
    restart: no
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom

  redis:
    image: redis
    networks:
      - custom

  app:
    restart: no
    depends_on:
      - local_db
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - custom

  worker:
    restart: no
    depends_on:
      - redis
    build:
      context: .
    networks:
      - custom
    command: [ "celery", "--workdir=./online_shop", "-A", "online_shop", "worker"]


networks:
  custom:
    driver: bridge
