# Generated by Django 5.0.4 on 2024-05-06 15:23
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0015_remove_orderitem_order_remove_orderitem_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(False, "В Пути"), (True, "Доставлен")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.TimeField(
                        auto_now_add=True, verbose_name="Время оформления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Размер"
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commerce.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
        migrations.CreateModel(
            name="ProductInCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Размер"
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Корзина",
            },
        ),
    ]
