# Generated by Django 5.0.4 on 2024-04-30 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_productincart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together={('user', 'product', 'size')},
        ),
    ]
