# Generated by Django 5.0.4 on 2024-05-01 05:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_alter_productincart_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productincart",
            unique_together=set(),
        ),
    ]
