# Generated by Django 5.0.4 on 2024-05-01 10:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0008_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.BooleanField(
                choices=[(False, "В Пути"), (True, "Доставлен")], default=0
            ),
        ),
    ]
