# Generated by Django 5.0.4 on 2024-05-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_order_created_at_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
