# Generated by Django 5.0.4 on 2024-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_remove_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
