# Generated by Django 5.0.4 on 2024-05-06 15:23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0014_alter_category_options_alter_favoriteproduct_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productincart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productincart",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="ProductInCart",
        ),
    ]
